# Generated by Django 4.2.1 on 2023-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('mentor', 'mentor')], max_length=50, null=True),
        ),
    ]
