# Generated by Django 4.2.1 on 2023-05-25 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('JS 31', 'JS 31'), ('PY 27', 'PY 27')], max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='social_media_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None),
        ),
    ]
