# Generated by Django 4.2.1 on 2023-05-25 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_group_alter_myuser_social_media_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='social_media_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
